instruments:
- symbol: 512800.SS
  name: 银行
  enabled: true
  risk_budget_pct: 0.01
  stop_atr_mul: 1.5
- symbol: 512000.SS
  name: 券商
  enabled: true
  risk_budget_pct: 0.01
  stop_atr_mul: 1.5
- symbol: 512200.SS
  name: 房地产
  enabled: true
  risk_budget_pct: 0.01
  stop_atr_mul: 1.5
- symbol: 159928.SZ
  name: 消费
  enabled: true
  risk_budget_pct: 0.01
  stop_atr_mul: 1.5
- symbol: 512690.SS
  name: 酒
  enabled: true
  risk_budget_pct: 0.01
  stop_atr_mul: 1.5
- symbol: 512010.SS
  name: 医药
  enabled: true
  risk_budget_pct: 0.01
  stop_atr_mul: 1.5
- symbol: 512290.SS
  name: 生物医药
  enabled: true
  risk_budget_pct: 0.01
  stop_atr_mul: 1.5
- symbol: 512760.SS
  name: 芯片
  enabled: true
  risk_budget_pct: 0.01
  stop_atr_mul: 1.5
- symbol: 515260.SS
  name: 电子
  enabled: true
  risk_budget_pct: 0.01
  stop_atr_mul: 1.5
- symbol: 515050.SS
  name: 5G
  enabled: true
  risk_budget_pct: 0.01
  stop_atr_mul: 1.5
- symbol: 159869.SZ
  name: 游戏
  enabled: true
  risk_budget_pct: 0.01
  stop_atr_mul: 1.5
- symbol: 515030.SS
  name: 新能源车
  enabled: true
  risk_budget_pct: 0.01
  stop_atr_mul: 1.5
- symbol: 515790.SS
  name: 光伏
  enabled: true
  risk_budget_pct: 0.01
  stop_atr_mul: 1.5
- symbol: 159755.SZ
  name: 电池
  enabled: true
  risk_budget_pct: 0.01
  stop_atr_mul: 1.5
- symbol: 515220.SS
  name: 煤炭
  enabled: true
  risk_budget_pct: 0.01
  stop_atr_mul: 1.5
- symbol: 512400.SS
  name: 有色金属
  enabled: true
  risk_budget_pct: 0.01
  stop_atr_mul: 1.5
- symbol: 515210.SS
  name: 钢铁
  enabled: true
  risk_budget_pct: 0.01
  stop_atr_mul: 1.5
- symbol: 512660.SS
  name: 军工
  enabled: true
  risk_budget_pct: 0.01
  stop_atr_mul: 1.5
- symbol: 516950.SS
  name: 基建50
  enabled: true
  risk_budget_pct: 0.01
  stop_atr_mul: 1.5
- symbol: 159825.SZ
  name: 农业
  enabled: true
  risk_budget_pct: 0.01
  stop_atr_mul: 1.5
